# Generated by Django 5.1.4 on 2026-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='e.g. /projects/old-slug/', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='e.g. /projects/new-slug/', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
