# Generated by Django 5.1.4 on 2026-10-04 14:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
