# Generated by Django 5.1.4 on 2026-10-02 09:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
